using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.Speech.AudioFormat;
using System.Speech.Synthesis;

namespace TextToSpeechAndSubtitles
{
    internal class SubtitleSpeechStateThing
    {
        private List<SubtitleUnit> _subtitleUnits = new List<SubtitleUnit>();
        private SynthesisFileInfo _fileInfo;
        private PromptBuilder _builder;
        private string[] _inputLines;
        private SubtitleOutput _subtitleStyle;
        private int _currentLine = 0;
        private int _lastLineStart = 0;
        private int _lastCharPos = 0;

        public SubtitleSpeechStateThing(SynthesisFileInfo fileInfo, SubtitleOutput subtitleOutput)
        {
            _fileInfo = fileInfo;
            _builder = new PromptBuilder();

            _inputLines = File.ReadAllLines(_fileInfo.InputFileName).Where(x => !string.IsNullOrWhiteSpace(x)).ToArray();

            for (int i = 0; i < _inputLines.Length; i++)
            {
                _builder.AppendText(_inputLines[i]);
                _builder.AppendBookmark(i.ToString());
            }

            _subtitleStyle = subtitleOutput;

        }

        public void DoSynthesisAndSubtitles()
        {
            using (SpeechSynthesizer synth = new SpeechSynthesizer())
            {
                //synth.SetOutputToWaveFile(fileInfo.AudioFileName, new SpeechAudioFormatInfo(32000, AudioBitsPerSample.Sixteen, AudioChannel.Mono));
                synth.SetOutputToDefaultAudioDevice();

                synth.SelectVoiceByHints(VoiceGender.Female);

                synth.SpeakProgress += synth_SpeakProgress;
                synth.BookmarkReached += synth_Bookmark;

                _currentLine = _lastCharPos = _lastLineStart = 0;
                synth.Speak(_builder);

                using (var fileStream = File.Open(_fileInfo.SubtitleFileName, FileMode.Create))
                {
                    //    subWriter.WriteStream(fileStream, subtitleItems);
                    fileStream.Write(Encoding.UTF8.GetBytes(
                        @"[Script Info]
; Script generated by Princess Grace's TextToSpeechAndSubtitles
ScriptType: v4.00
WrapStyle: Smart

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"
                        ));

                    foreach (var unit in _subtitleUnits)
                    {
                        var startTimestamp = unit.StartTime.ToString(@"h\:mm\:ss\.ff");
                        var endTimestamp = unit.EndTime.ToString(@"h\:mm\:ss\.ff");
                        fileStream.Write(Encoding.UTF8.GetBytes($"Dialogue: 0,{startTimestamp},{endTimestamp},Default,,0,0,0,,{unit.Text}\r\n"));
                    }
                }

            }

            void synth_SpeakProgress(object sender, SpeakProgressEventArgs e)
            {
                Console.WriteLine("CharPos: {0}   CharCount: {1}   AudioPos: {2}    \"{3}\"",
                  e.CharacterPosition, e.CharacterCount, e.AudioPosition, e.Text);

                TimeSpan pos = e.AudioPosition;

                var lastSub = _subtitleUnits.LastOrDefault();
                if (lastSub is not null)
                {
                    lastSub.EndTime = pos;
                }

                var subText = _subtitleStyle == SubtitleOutput.Words ? 
                    e.Text :
                    FindSubstringEndingInSpokenWord(_inputLines[_currentLine].Substring(_lastLineStart, Math.Min(e.CharacterPosition + e.CharacterCount, _inputLines[_currentLine].Length)), e.Text);
                _lastCharPos = e.CharacterPosition + e.CharacterCount;
                Console.WriteLine(subText);
                _subtitleUnits.Add(new SubtitleUnit
                {
                    StartTime = pos,
                    EndTime = TimeSpan.MaxValue,
                    Text = subText
                });
            }

            void synth_Bookmark(object sender, BookmarkReachedEventArgs e)
            {
                _currentLine = int.Parse(e.Bookmark);
                _lastLineStart = _lastCharPos;
            }

        }

        private string FindSubstringEndingInSpokenWord(string haystack, string needle)
        {
            // todo: handle when words are substrings of other words, like "a"
            return haystack.Substring(0, haystack.LastIndexOf(needle) + needle.Length);
        }

        public void MakeWavFile()
        {
            using (SpeechSynthesizer synth = new SpeechSynthesizer())
            {
                synth.SetOutputToWaveFile(_fileInfo.AudioFileName, new SpeechAudioFormatInfo(32000, AudioBitsPerSample.Sixteen, AudioChannel.Mono));

                synth.SelectVoiceByHints(VoiceGender.Female);

                synth.Speak(_builder);
            }

        }

        class SubtitleUnit
        {
            public TimeSpan StartTime;
            public TimeSpan EndTime;
            public string Text = string.Empty;
        }

        public enum SubtitleOutput
        {
            Words,
            Paragraphs
        }
    }
}
